#!/usr/bin/env bash
# scripts/discover-project-ids.sh
# Discover the opaque Projects v2 IDs for the harness and write .env.demo.
# Safe to re-run — overwrites .env.demo each time.
#
# Usage:
#   scripts/discover-project-ids.sh --owner <user-or-org> --repo <repo> --project-number <N>
#
# Prerequisite: the project must exist and its Status field must have exactly
# these four options: Ready, In Progress, In Review, Done. Run bootstrap.sh
# first to guarantee this.

set -euo pipefail

GITHUB_OWNER=""
GITHUB_REPO=""
PROJECT_NUMBER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --owner)          GITHUB_OWNER="$2";   shift 2 ;;
    --repo)           GITHUB_REPO="$2";    shift 2 ;;
    --project-number) PROJECT_NUMBER="$2"; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$GITHUB_OWNER"    ]] && { echo "Missing --owner"          >&2; exit 1; }
[[ -z "$GITHUB_REPO"     ]] && { echo "Missing --repo"           >&2; exit 1; }
[[ -z "$PROJECT_NUMBER"  ]] && { echo "Missing --project-number" >&2; exit 1; }

command -v gh >/dev/null 2>&1 || { echo "gh CLI not installed" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "jq not installed"      >&2; exit 1; }

# ─── PROJ_ID ───────────────────────────────────────────────────────────────
PROJ_ID=$(gh api graphql -f query='
  query($login:String!, $number:Int!) {
    user(login:$login)         { projectV2(number:$number) { id } }
    organization(login:$login) { projectV2(number:$number) { id } }
  }' -f login="$GITHUB_OWNER" -F number="$PROJECT_NUMBER" \
  --jq '.data.user.projectV2.id // .data.organization.projectV2.id')

if [[ -z "$PROJ_ID" || "$PROJ_ID" == "null" ]]; then
  echo "Could not find project #$PROJECT_NUMBER under $GITHUB_OWNER" >&2
  echo "Verify with: gh project list --owner $GITHUB_OWNER" >&2
  exit 1
fi

# ─── STATUS_FIELD_ID + option IDs ──────────────────────────────────────────
STATUS_JSON=$(gh api graphql -f query='
  query($proj:ID!) {
    node(id:$proj) {
      ... on ProjectV2 {
        field(name:"Status") {
          ... on ProjectV2SingleSelectField { id options { id name } }
        }
      }
    }
  }' -f proj="$PROJ_ID")

STATUS_FIELD_ID=$(echo "$STATUS_JSON" | jq -r '.data.node.field.id')

if [[ -z "$STATUS_FIELD_ID" || "$STATUS_FIELD_ID" == "null" ]]; then
  echo "Project has no 'Status' single-select field. Run bootstrap.sh to configure." >&2
  exit 1
fi

get_option() {
  local name="$1"
  echo "$STATUS_JSON" | jq -r --arg n "$name" '.data.node.field.options[] | select(.name==$n) | .id'
}

READY_OPTION_ID=$(get_option "Ready")
IN_PROGRESS_OPTION_ID=$(get_option "In Progress")
IN_REVIEW_OPTION_ID=$(get_option "In Review")
DONE_OPTION_ID=$(get_option "Done")

for pair in \
  "READY:$READY_OPTION_ID" \
  "IN_PROGRESS:$IN_PROGRESS_OPTION_ID" \
  "IN_REVIEW:$IN_REVIEW_OPTION_ID" \
  "DONE:$DONE_OPTION_ID"
do
  name="${pair%%:*}"; val="${pair#*:}"
  if [[ -z "$val" ]]; then
    echo "Status field is missing option '$name'. Run bootstrap.sh to configure options." >&2
    exit 1
  fi
done

# ─── Write .env.demo ───────────────────────────────────────────────────────
cat > .env.demo <<ENVDEMO
# Generated by scripts/discover-project-ids.sh — DO NOT COMMIT.
# Source in your shell:  source .env.demo
export GITHUB_OWNER="$GITHUB_OWNER"
export GITHUB_REPO="$GITHUB_REPO"
export PROJECT_NUMBER="$PROJECT_NUMBER"
export PROJ_ID="$PROJ_ID"
export STATUS_FIELD_ID="$STATUS_FIELD_ID"
export READY_OPTION_ID="$READY_OPTION_ID"
export IN_PROGRESS_OPTION_ID="$IN_PROGRESS_OPTION_ID"
export IN_REVIEW_OPTION_ID="$IN_REVIEW_OPTION_ID"
export DONE_OPTION_ID="$DONE_OPTION_ID"
ENVDEMO

echo "✓ A5. .env.demo written (owner=$GITHUB_OWNER, repo=$GITHUB_REPO, project=#$PROJECT_NUMBER)"
echo "     Load in your shell:  source .env.demo"
